Repository open-telemetry/opentelemetry-demo, pull requests merged in 2022-12, with the labels that each got.

#612 [adservice] add some hints when missing port config.
  src/adservice/src/main/java/hipstershop/AdService.java
Labels: in-progress

#615 support non-root containers
  CHANGELOG.md
  docker-compose.yml
  src/adservice/Dockerfile
  src/emailservice/Dockerfile
  src/frauddetectionservice/Dockerfile
  src/frontendproxy/Dockerfile
  src/quoteservice/Dockerfile
Labels: in-progress

#613 [FrontendProxy] Add tracing to Envoy
  .env
  CHANGELOG.md
  docker-compose.yml
  docs/services/frontendproxy.md
  src/frontendproxy/envoy.tmpl.yaml
Labels: enhancement, in-progress

#655 Jaeger-SPM-Config
  .env
  CHANGELOG.md
  docker-compose.yml
Labels: helm-update-required
