Repository open-telemetry/opentelemetry-demo, pull requests merged in 2022-10, with the labels that each got.

#404 Doc/improve mermaid chart
  README.md
Labels: documentation, enhancement

#418 [featureflag] document instrumentation
  docs/services/featureflagservice.md
Labels: documentation

#434 [frontend] fix local development instructions and dependencies
  docker-compose.yml
  src/frontend/Dockerfile
  src/frontend/README.md
Labels: bug

#489 CarService - refactor to modern template
  src/cartservice/src/Program.cs
  src/cartservice/src/Startup.cs
Labels: v1-review

#486 License updates to be consistent on new services
  docker-compose.yml
  src/currencyservice/src/server.cpp
  src/currencyservice/src/tracer_common.h
  src/emailservice/Dockerfile
  src/emailservice/email_server.rb
  src/featureflagservice/src/ffs_service.erl
  src/frontend/pages/index.tsx
  src/quoteservice/public/index.php
  src/shippingservice/src/main.rs
  test/test.js
Labels: v1-review

#490 Readme refactor
  CONTRIBUTING.md
  README.md
  docs/README.md
  docs/current_architecture.md
  docs/demo_features.md
  docs/service_table.md
  docs/services/shippingservice.md
  docs/tests.md
Labels: v1-review

#522 fix currency bug
  src/frontend/components/CartItems/CartItems.tsx
  src/frontend/gateways/Api.gateway.ts
  src/frontend/pages/api/shipping.ts
  src/frontend/services/ProductCatalog.service.ts
Labels: v1-required

#521 [docs] kubernetes
  docs/kubernetes_deployment.md
Labels: v1-required
