Repository open-telemetry/opentelemetry-demo, pull requests merged in 2023-01, with the labels that each got.

#670 [frontend] Fix minor bugs
  .dockerignore
  src/frontend/components/CartDropdown/CartDropdown.styled.ts
  src/frontend/components/CartDropdown/CartDropdown.tsx
  src/frontend/pages/_document.tsx
Labels: enhancement

#669 [loadgenerator] Bump deps and update container base image
  CHANGELOG.md
  src/loadgenerator/Dockerfile
  src/loadgenerator/locustfile.py
  src/loadgenerator/people.json
  src/loadgenerator/requirements.txt
Labels: enhancement

#661 Add healthcheck to featureflagservice
  CHANGELOG.md
  docker-compose.yml
  src/featureflagservice/Dockerfile
Labels: helm-update-required

#700 [recommendationservice] - base image, licensing and diagram update
  .dockerignore
  CHANGELOG.md
  docs/current_architecture.md
  src/recommendationservice/Dockerfile
  src/recommendationservice/logger.py
  src/recommendationservice/recommendation_server.py
  src/recommendationservice/requirements.txt
Labels: for-next-release

#703 Update emailservice Dockerfile to use alpine and multistage build
  CHANGELOG.md
  src/emailservice/.dockerignore
  src/emailservice/Dockerfile
Labels: for-next-release

#705 Update dockerfile for adservice to use different base images
  CHANGELOG.md
  src/adservice/Dockerfile
Labels: for-next-release

#704 Enable exemplar export/display support
  CHANGELOG.md
  docker-compose.yml
  docs/demo_features.md
  docs/metric_service_features.md
  src/grafana/provisioning/dashboards/general/demo-dashboard.json
  src/grafana/provisioning/datasources/default.yaml
  src/otelcollector/otelcol-config.yml
Labels: for-next-release

#694 Add random errors in AdService
  CHANGELOG.md
  docker-compose.yml
  docs/current_architecture.md
  docs/feature_flags.md
  src/adservice/Dockerfile
  src/adservice/README.md
  src/adservice/settings.gradle
  src/adservice/src/main/java/hipstershop/AdService.java
  src/featureflagservice/priv/repo/migrations/20220524172636_create_featureflags.exs
Labels: helm-update-required, for-next-release

#632 feature(frontend): adding instrumentation metrics
  docker-compose.yml
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/utils/telemetry/Instrumentation.js
  src/frontend/utils/telemetry/InstrumentationMiddleware.ts
Labels: helm-update-required, for-next-release

#718 Updated demo link for Sumo Logic
  README.md
Labels: v1.4

#657 Add build for arm64 arch
  .github/workflows/release.yml
  CHANGELOG.md
Labels: v1.4
