Repository open-telemetry/opentelemetry-demo, pull requests merged in 2023-03, with the labels that each got.

#787 spanmetrics dashboard premiere
  CHANGELOG.md
  src/grafana/provisioning/dashboards/general/spanmetrics-dashboard.json
Labels: helm-update-required, v1.4

#790 [chore] generate Kubernetes manifests (part 1)
  .yamlignore
  .yamllint
  Makefile
Labels: v1.4

#779 [cart] use 60m TTL for cart cache
  CHANGELOG.md
  src/cartservice/src/cartstore/RedisCartStore.cs
Labels: v1.4

#793 fixing quoteservice metrics exporting
  CHANGELOG.md
  docker-compose.yml
  src/quoteservice/composer.json
  src/quoteservice/public/index.php
Labels: helm-update-required

#809 Otlp env variables
  .env
  docker-compose.yml
Labels: helm-update-required, v1.4

#798 reduce kafka mem allocation
  docker-compose.yml
  src/kafka/Dockerfile
Labels: helm-update-required, v1.4
