Repository open-telemetry/opentelemetry-demo, pull requests merged in 2023-05, with the labels that each got.

#857 [collector] update collector to 0.76.1 and remove connectors feature gates
  CHANGELOG.md
  docker-compose.yml
  src/grafana/provisioning/dashboards/general/spanmetrics-dashboard.json
Labels: helm-update-required

#865 [shippingservice] update rust version and dependencies
  CHANGELOG.md
  src/shippingservice/Cargo.lock
  src/shippingservice/Cargo.toml
  src/shippingservice/Dockerfile
Labels: rust

#869 [load generator] Bump loagen dependencies
  CHANGELOG.md
  src/loadgenerator/locustfile.py
  src/loadgenerator/requirements.txt
Labels: python
